# Generated by Django 4.0.3 on 2022-03-11 03:51

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('majorproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='', storage=djongo.storage.GridFSStorage(collection='songs'), upload_to='songs'),
        ),
    ]
